#server port
server:
  port: 80
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
########################################################
###FREEMARKER (FreeMarkerAutoConfiguration)
########################################################
spring:
  freemarker:
    allow-request-override: false
    cache: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
    #    prefix=
    #    settings.*=
    #    suffix=.ftl
    #    template-loader-path=classpath:/templates/ #comma-separated list
    #    view-names= # whitelist of view names that can be resolved
  datasource:
      druid:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://qdm163903142.my3w.com:3306/qdm163903142_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
#        username: qdm163903142
#        password: yanzi123
        url: jdbc:mysql://localhost:3306/lazydsr-manager?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: root
        initialSize: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true

#使用开发时日志配置
logging:
  config: classpath:config/logback-spring.xml

